# Generated by Django 5.2.17 on 2026-09-11 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=64, unique=True, verbose_name='ID Stasiun')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Posko / Lokasi')),
                ('latitude', models.FloatField(default=-6.2088, verbose_name='Latitude (Lintang)')),
                ('longitude', models.FloatField(default=106.8456, verbose_name='Longitude (Bujur)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi / Catatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Registrasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Terakhir')),
            ],
            options={
                'verbose_name': 'Stasiun Sensor',
                'verbose_name_plural': 'Daftar Stasiun Sensor',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DisasterAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('QUAKE', 'Gempa Bumi / Seismik'), ('FLOOD', 'Banjir / Luapan Air'), ('COMBINED', 'Bencana Multi-Kondisi')], default='QUAKE', max_length=32, verbose_name='Jenis Bencana')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Peringatan')),
                ('description', models.TextField(verbose_name='Keterangan Peringatan')),
                ('severity', models.CharField(default='AWAS', max_length=32, verbose_name='Tingkat Keparahan')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Magnitudo')),
                ('water_level_cm', models.FloatField(blank=True, null=True, verbose_name='Tinggi Air (cm)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Kejadian')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.sensorstation')),
            ],
            options={
                'verbose_name': 'Peringatan Dini (EWS Alert)',
                'verbose_name_plural': 'Riwayat Peringatan Dini EWS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pga_g', models.FloatField(default=0.002, verbose_name='PGA (g)')),
                ('gal', models.FloatField(default=1.96, verbose_name='Akselerasi Gal (cm/s²)')),
                ('magnitude', models.FloatField(default=0.0, verbose_name='Estimasi Magnitudo (SR)')),
                ('frequency_hz', models.FloatField(default=0.2, verbose_name='Frekuensi (Hz)')),
                ('mmi_scale', models.CharField(default='I (Tidak Terasa)', max_length=64, verbose_name='Skala MMI')),
                ('seismic_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WASPADA', 'Waspada'), ('SIAGA', 'Siaga'), ('AWAS', 'Awas / Bahaya')], default='NORMAL', max_length=32, verbose_name='Status Gempa')),
                ('water_level_cm', models.FloatField(default=42.5, verbose_name='Ketinggian Air (cm)')),
                ('flood_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WASPADA', 'Waspada'), ('SIAGA', 'Siaga'), ('AWAS', 'Awas / Bahaya')], default='NORMAL', max_length=32, verbose_name='Status Banjir')),
                ('rain_rate_mmh', models.FloatField(default=0.0, verbose_name='Curah Hujan (mm/jam)')),
                ('rain_raw_analog', models.IntegerField(default=4095, verbose_name='Nilai Analog Hujan')),
                ('rain_condition', models.CharField(default='Cerah / Tidak Hujan', max_length=64, verbose_name='Kondisi Hujan')),
                ('tds_ppm', models.FloatField(default=148.0, verbose_name='Partikel TDS (PPM)')),
                ('water_quality', models.CharField(default='Air Bersih / Layak', max_length=64, verbose_name='Kualitas Air')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Waktu Perekaman')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='monitoring.sensorstation')),
            ],
            options={
                'verbose_name': 'Log Telemetri Sensor',
                'verbose_name_plural': 'Riwayat Telemetri Sensor',
                'ordering': ['-timestamp'],
            },
        ),
    ]
